Added training data
kewlamogh/training-poc pull request #3
Opened 2023-04-14 14:40 UTC by kewlamogh

Added more training data

2023-04-14 14:46 UTC, kewlamogh commented
I don't know, maybe it is necessary. I kind of wanted to reinforce this - maybe it would cause the ML model to take that particular line of training data more seriously

2023-04-14 14:47 UTC, aashishkewlie requested changes
This is not necessary.Please remove.

2023-04-14 14:48 UTC, kewlamogh commented on training_data.jsonl
> +{"prompt": "Understand these logs and diagnose a problem and a solution: Apr 6 10:30:34 server1 rsyslogd: [origin software=\"rsyslogd\" swVersion=\"8.16.0\" x-pid=\"2073\" x-info=\"http://www.rsyslog
I don't know, maybe it is necessary. I kind of wanted to reinforce this - maybe it would cause the ML model to take that particular line of training data more seriously

2023-04-14 14:49 UTC, kewlamogh commented on training_data.jsonl
> +{"prompt": "Understand these logs and diagnose a problem and a solution: Apr 6 10:30:34 server1 rsyslogd: [origin software=\"rsyslogd\" swVersion=\"8.16.0\" x-pid=\"2073\" x-info=\"http://www.rsyslog
Done

2023-04-18 13:18 UTC, aashishkewlie approved these changes
looks good

2023-04-26 07:47 UTC, aashishkewlie approved these changes

2023-04-27 00:44 UTC, closed without merging